import {
  UserProfile,
  RFQ,
  RFQUpdate,
  Quotation,
  Product,
  Project,
  Capability,
  Industry,
  Notification,
} from "@/types";

export const SEED_PROFILES: UserProfile[] = [
  // Admins
  {
    id: "usr-admin-01",
    user_id: "auth-admin-01",
    full_name: "Vikramaditya Mehta",
    company_name: "STEELCORE INDUSTRIES",
    email: "admin@steelcoreindustries.com",
    phone: "+91 98230 11001",
    role: "ADMIN",
    designation: "VP - Plant Operations & Estimation",
    city: "Pune",
    state: "Maharashtra",
    gstin: "27AAACS1234F1Z8",
    created_at: "2024-01-10T09:00:00Z",
    updated_at: "2026-09-01T10:00:00Z",
  },
  {
    id: "usr-admin-02",
    user_id: "auth-admin-02",
    full_name: "Rajesh Kulkarni",
    company_name: "STEELCORE INDUSTRIES",
    email: "rajesh.k@steelcoreindustries.com",
    phone: "+91 98230 11002",
    role: "ADMIN",
    designation: "Chief Metallurgical & Fabrication Engineer",
    city: "Pune",
    state: "Maharashtra",
    gstin: "27AAACS1234F1Z8",
    created_at: "2024-01-15T09:00:00Z",
    updated_at: "2026-09-05T10:00:00Z",
  },
  // 10 B2B Customers
  {
    id: "usr-cust-01",
    user_id: "auth-cust-01",
    full_name: "Rahul Sharma",
    company_name: "ABC Infrastructure Pvt Ltd",
    email: "rahul@abc.com",
    phone: "+91 98112 34567",
    role: "CUSTOMER",
    designation: "Head of Procurement",
    city: "Mumbai",
    state: "Maharashtra",
    gstin: "27AABCA1234F1Z5",
    created_at: "2025-02-10T11:00:00Z",
    updated_at: "2026-08-10T12:00:00Z",
  },
  {
    id: "usr-cust-02",
    user_id: "auth-cust-02",
    full_name: "Amit Patel",
    company_name: "L&T Heavy Engineering Division",
    email: "amit.patel@lnt-heavy.com",
    phone: "+91 98220 87654",
    role: "CUSTOMER",
    designation: "Senior Project Director",
    city: "Surat",
    state: "Gujarat",
    gstin: "24AABCL9876E1Z2",
    created_at: "2025-03-01T08:30:00Z",
    updated_at: "2026-08-20T14:15:00Z",
  },
  {
    id: "usr-cust-03",
    user_id: "auth-cust-03",
    full_name: "Sunil Deshmukh",
    company_name: "Tata Projects Infra Unit",
    email: "sunil.d@tataprojects.corp",
    phone: "+91 99231 45678",
    role: "CUSTOMER",
    designation: "VP - Supply Chain",
    city: "Pune",
    state: "Maharashtra",
    gstin: "27AAACT5555G1Z9",
    created_at: "2025-04-12T10:00:00Z",
    updated_at: "2026-09-02T16:00:00Z",
  },
  {
    id: "usr-cust-04",
    user_id: "auth-cust-04",
    full_name: "Karthik Subramanian",
    company_name: "Mahindra Solar Energy Corp",
    email: "karthik.s@mahindrasolar.in",
    phone: "+91 94440 98712",
    role: "CUSTOMER",
    designation: "Procurement Manager",
    city: "Chennai",
    state: "Tamil Nadu",
    gstin: "33AABCM3333F1Z1",
    created_at: "2025-05-18T12:00:00Z",
    updated_at: "2026-08-15T09:00:00Z",
  },
  {
    id: "usr-cust-05",
    user_id: "auth-cust-05",
    full_name: "Vikram Rathore",
    company_name: "JSW Energy Logistics",
    email: "v.rathore@jswenergy.in",
    phone: "+91 98290 11223",
    role: "CUSTOMER",
    designation: "Engineering Lead",
    city: "Jaipur",
    state: "Rajasthan",
    gstin: "08AABCJ7777D1Z4",
    created_at: "2025-06-22T14:30:00Z",
    updated_at: "2026-07-28T11:20:00Z",
  },
  {
    id: "usr-cust-06",
    user_id: "auth-cust-06",
    full_name: "Priya Menon",
    company_name: "Godrej Aerospace & Precision Units",
    email: "pmenon@godrej-precision.com",
    phone: "+91 98450 67890",
    role: "CUSTOMER",
    designation: "Quality & Sourcing Specialist",
    city: "Bengaluru",
    state: "Karnataka",
    gstin: "29AABCG8888H1Z7",
    created_at: "2025-07-05T09:15:00Z",
    updated_at: "2026-08-30T10:45:00Z",
  },
  {
    id: "usr-cust-07",
    user_id: "auth-cust-07",
    full_name: "Anand Verma",
    company_name: "Shapoorji PEB Systems Ltd",
    email: "anand.verma@shapoorji.in",
    phone: "+91 99100 44556",
    role: "CUSTOMER",
    designation: "Chief Structural Engineer",
    city: "Gurugram",
    state: "Haryana",
    gstin: "06AABCS4444C1Z3",
    created_at: "2025-08-14T11:45:00Z",
    updated_at: "2026-09-04T15:20:00Z",
  },
  {
    id: "usr-cust-08",
    user_id: "auth-cust-08",
    full_name: "Suresh Reddy",
    company_name: "Hyderabad Metro Line Components",
    email: "suresh.reddy@hydmetro-infra.org",
    phone: "+91 98490 22334",
    role: "CUSTOMER",
    designation: "Technical Director",
    city: "Hyderabad",
    state: "Telangana",
    gstin: "36AABCH9999K1Z8",
    created_at: "2025-09-09T16:00:00Z",
    updated_at: "2026-08-25T17:10:00Z",
  },
  {
    id: "usr-cust-09",
    user_id: "auth-cust-09",
    full_name: "Naveen Singhal",
    company_name: "Bharat Forge Ancillary Tech",
    email: "naveen.s@bf-ancillary.co.in",
    phone: "+91 98224 88990",
    role: "CUSTOMER",
    designation: "Materials Sourcing Manager",
    city: "Pune",
    state: "Maharashtra",
    gstin: "27AABCB1111L1Z0",
    created_at: "2025-10-11T13:20:00Z",
    updated_at: "2026-09-03T11:00:00Z",
  },
  {
    id: "usr-cust-10",
    user_id: "auth-cust-10",
    full_name: "Deepak Chawla",
    company_name: "BHEL Industrial Boiler Division",
    email: "deepak.c@bhel-power.gov.in",
    phone: "+91 97112 55667",
    role: "CUSTOMER",
    designation: "General Manager - Fabrication",
    city: "Bhopal",
    state: "Madhya Pradesh",
    gstin: "23AAACB6666M1Z2",
    created_at: "2025-11-20T10:10:00Z",
    updated_at: "2026-09-06T14:00:00Z",
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: "prod-01",
    name: "Heavy Structural Steel Beams (ISMB / UB)",
    slug: "structural-steel-beams",
    category: "Steel Products",
    subcategory: "Structural Steel",
    short_description:
      "Hot-rolled structural I-beams & Universal Beams engineered to IS 2062 / EN 10025 for heavy infrastructure and PEB framing.",
    description:
      "Our heavy structural steel beams are precision manufactured in compliance with IS 2062 Grade E250/E350 and ASTM A36/A992. Designed for bridges, commercial high-rises, industrial factories, and heavy crane gantries. Available in standard ISMB 150 to ISMB 600, along with European UB and UC profiles up to 914mm depth. High tensile strength, guaranteed weldability, and strict dimensional tolerances.",
    material: "Steel",
    grades: ["IS 2062 E250 BR/BO", "IS 2062 E350", "ASTM A36", "EN 10025 S355JR"],
    specifications: {
      "Standard Profile Range": "ISMB 150 to ISMB 600, UB 203x133 to 914x419",
      "Standard Lengths": "6m, 12m, and custom cut lengths up to 18m",
      "Tensile Strength": "410 - 540 MPa (Grade E250), 490 - 620 MPa (Grade E350)",
      "Yield Strength": "Min 250 MPa / Min 350 MPa",
      "Surface Finish": "Shot blasted SA 2.5, Red oxide or zinc silicate primer",
      "Tolerances": "Conforms strictly to IS 1852",
    },
    applications: [
      "Industrial factory warehouses and portal frames",
      "Flyover and highway bridge girders",
      "Heavy equipment foundations and crane runways",
      "Pre-engineered steel building (PEB) columns",
    ],
    manufacturing_process: [
      "High-temperature hot rolling from certified steel billets",
      "Controlled thermal mechanical cooling (TMT)",
      "Automated hydraulic straightness leveling",
      "Rotary cold sawing to precision tolerances",
      "Ultrasonic testing for internal lamination check",
    ],
    technical_info: {
      "Flange Slope": "14% slope (ISMB) / Parallel Flange (NPB / WPB)",
      "Welding Compatibility": "Pre-qualified for SMAW, GMAW, and SAW processes",
      "Inspection Standard": "Level 2 UT inspection, Mill Test Certificate (MTC 3.1)",
      "Corrosion Protection": "Factory epoxy primer option available",
    },
    image_url:
      "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80",
    is_featured: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-02",
    name: "Structural Steel Channels (ISMC)",
    slug: "structural-steel-channels",
    category: "Steel Products",
    subcategory: "Structural Steel",
    short_description:
      "C-section steel channels offering exceptional lateral stiffness for purlins, automotive chassis, and bracing systems.",
    description:
      "Precision-rolled ISMC channels manufactured to IS 2062 Grade E250 and ASTM A36. These channels provide superior structural support for industrial purlins, side cladding runners, truck chassis side rails, and electrical transmission towers. Strict dimensional adherence ensures rapid on-site assembly and minimal fabrication prep time.",
    material: "Steel",
    grades: ["IS 2062 E250A", "IS 2062 E350", "ASTM A36"],
    specifications: {
      "Profile Sizes": "ISMC 75x40 up to ISMC 400x100",
      "Lengths": "Standard 6m / 11.5m / 12m or customized",
      "Flange Slope": "Tapered flange 9% slope",
      "Tolerances": "IS 1852 specification limits",
    },
    applications: [
      "Roof purlins and wall girts in pre-engineered buildings",
      "Commercial vehicle chassis cross-members",
      "Electrical transmission tower assemblies",
      "Mezzanine floor joists and bracing",
    ],
    manufacturing_process: [
      "Continuous billet reheating",
      "Multi-stand continuous channel rolling mill",
      "Cooling bed controlled cooling",
      "Multi-roll inline straightening",
    ],
    technical_info: {
      "Weldability": "Superior carbon equivalent (<0.42%) ensures crack-free welds",
      "Testing": "Bend test 180° without cracking, Charpy V-notch at 0°C (E250BR)",
    },
    image_url:
      "https://images.unsplash.com/photo-1535813547-99c456a41d4a?auto=format&fit=crop&w=800&q=80",
    is_featured: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-03",
    name: "Structural Equal & Unequal Angles (ISA)",
    slug: "structural-steel-angles",
    category: "Steel Products",
    subcategory: "Structural Steel",
    short_description:
      "Heavy structural steel angle sections designed for transmission towers, bridge trusses, and equipment skids.",
    description:
      "Hot-rolled equal and unequal angle sections produced from prime billets. Ideal for high-stress triangulation in industrial trusses, power transmission towers, telecom structures, and modular skid frames. Excellent formability, drilling properties, and galvanized coating adherence.",
    material: "Steel",
    grades: ["IS 2062 E250", "IS 2062 E350", "BS EN 10025 S275JR"],
    specifications: {
      "Equal Angles": "ISA 25x25x3mm to 200x200x25mm",
      "Unequal Angles": "ISA 45x30x4mm to 200x150x18mm",
      "Tensile Strength": "410 - 540 MPa",
      "Elongation": "Min 23%",
    },
    applications: [
      "High voltage electrical transmission towers",
      "Telecommunication and microwave towers",
      "Industrial crane booms and conveyor support frameworks",
      "Machinery bases and foundation frames",
    ],
    manufacturing_process: [
      "Fully automated hot rolling line",
      "Precision corner radius cooling control",
      "Hydraulic straightening and bundle strapping",
    ],
    technical_info: {
      "Galvanizing Suitability": "Silicon content optimized (Si < 0.04% or 0.15% - 0.25%) for Class 1 HDG",
    },
    image_url:
      "https://images.unsplash.com/photo-1565514020179-026b92b84bb6?auto=format&fit=crop&w=800&q=80",
    is_featured: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-04",
    name: "High-Strength Steel Plates (IS 2062 E250 / E350)",
    slug: "high-strength-steel-plates",
    category: "Steel Products",
    subcategory: "Steel Plates",
    short_description:
      "Mill-certified heavy steel plates up to 120mm thickness for pressure vessels, wind towers, and fabricated girders.",
    description:
      "Heavy industrial grade hot-rolled steel plates supplied in normalized, thermo-mechanically controlled processed (TMCP), or as-rolled conditions. Featuring ultrasonic cleanliness conforming to ASTM A435/A578 Level II, these plates deliver reliable performance in seismic zones, offshore rigs, earthmoving buckets, and heavy pressure vessels.",
    material: "Steel",
    grades: ["IS 2062 E250 BR/BO", "IS 2062 E350", "SA 516 Gr 70", "Hardox / Abrasion Resistant Equivalent"],
    specifications: {
      "Thickness Range": "5mm to 120mm",
      "Widths": "1500mm, 2000mm, 2500mm, 3000mm",
      "Lengths": "Up to 14,000mm",
      "Impact Toughness": "Charpy V-Notch at -20°C / -40°C available",
    },
    applications: [
      "Fabricated welded box girders and bridge piers",
      "Heavy industrial pressure vessels and heat exchangers",
      "Wind turbine tower shell fabrication",
      "Excavator arms and crushing machine liners",
    ],
    manufacturing_process: [
      "Continuous slab casting with vacuum degassing",
      "High-pressure water descaling",
      "4-High heavy plate reversible rolling mill",
      "In-line roller leveling and ultrasonic testing",
    ],
    technical_info: {
      "Edge Condition": "Mill edge or CNC plasma trimmed bevel edge ready for welding",
      "Certification": "EN 10204 3.1 & 3.2 third-party inspection (TUV / DNV / BV)",
    },
    image_url:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
    is_featured: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-05",
    name: "Heavy Steel Pipes & Hollow Sections (SHS / RHS / CHS)",
    slug: "steel-pipes-hollow-sections",
    category: "Steel Products",
    subcategory: "Steel Pipes",
    short_description:
      "Seamless and high-frequency ERW hollow sections offering superior torsional resistance for architectural structures.",
    description:
      "Square, rectangular, and circular hollow sections produced to IS 4923 / EN 10219. Providing clean architectural aesthetics coupled with extreme torsional and buckling strength. Widely utilized in airport terminal roofs, sports stadiums, industrial sheds, and mechanical piping systems.",
    material: "Steel",
    grades: ["IS 4923 YSt 210/310/355", "ASTM A500 Grade B/C", "IS 1239 / IS 3589"],
    specifications: {
      "Square Sections (SHS)": "25x25x2mm to 400x400x16mm",
      "Rectangular Sections (RHS)": "50x25x2.5mm to 500x300x16mm",
      "Circular Pipes (CHS)": "21.3mm OD to 610mm OD (up to 20mm wall)",
      "Standard Lengths": "6m / 12m or customized project cuts",
    },
    applications: [
      "Airport terminals and monumental architectural space frames",
      "Highway overhead signage gantries and toll plaza canopies",
      "Conveyor galleries and mining structural supports",
      "High-pressure fluid & gas transportation lines",
    ],
    manufacturing_process: [
      "Continuous ERW high-frequency roll forming",
      "Inline weld seam heat treatment (seam annealing)",
      "Eddy current non-destructive testing",
      "Hydrostatic pressure testing up to 50 bar",
    ],
    technical_info: {
      "Corner Radius": "Strict compliance with EN 10219 for tight joint fit-up",
      "Corrosion Defense": "Internal and external varnish or hot-dip galvanizing",
    },
    image_url:
      "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=800&q=80",
    is_featured: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-06",
    name: "Custom Welded Box Girders & Built-up Columns",
    slug: "custom-steel-fabrication",
    category: "Custom Products",
    subcategory: "Custom Steel Fabrication",
    short_description:
      "Engineered-to-order heavy welded structural box columns, crane girders, and plate girders for monumental loads.",
    description:
      "Our dedicated heavy fabrication shop engineers complex built-up members including submerged arc welded (SAW) box girders, variable depth plate girders, and cruciform columns. Every fabricated assembly undergoes full non-destructive testing (NDT), dimensional surveying with laser trackers, and shop pre-assembly to guarantee zero on-site erection surprises.",
    material: "Steel",
    grades: ["IS 2062 E350 / E450", "ASTM A572 Gr 50", "EN 10025 S355K2+N"],
    specifications: {
      "Maximum Fabrication Depth": "Up to 3,500mm single girder depth",
      "Maximum Piece Weight": "Up to 60 Metric Tons per individual piece",
      "Welding Quality": "WPS/PQR qualified to AWS D1.1 / ASME Sec IX",
      "Paint System": "3-Coat epoxy-polyurethane system up to 350 microns DFT",
    },
    applications: [
      "Metro rail viaducts and railway over-bridges (ROBs)",
      "High-capacity EOT crane runway girders (up to 250T crane rating)",
      "Thermal power plant and refinery boiler supporting columns",
      "Convention centers and column-free exhibition halls",
    ],
    manufacturing_process: [
      "CNC 5-axis bevel plasma cutting",
      "Hydraulic tacking and alignment jig fixture",
      "Automated twin-wire Submerged Arc Welding (SAW)",
      "100% Ultrasonic & Radiographic testing of butt welds",
      "Automated shot blasting to SA 2.5 and airless spray coating",
    ],
    technical_info: {
      "Weld Inspection": "100% UT on tension flange welds, 100% MPI on fillet welds",
      "Trial Assembly": "3D shop trial assembly with calibrated total station",
    },
    image_url:
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
    is_featured: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-07",
    name: "Industrial Aluminium Modular T-Slot Profiles",
    slug: "aluminium-modular-t-slot-profiles",
    category: "Aluminium Products",
    subcategory: "Aluminium Profiles",
    short_description:
      "Precision anodized aluminium modular extrusion profiles for machine frames, robotic cells, and conveyor systems.",
    description:
      "Extruded from high-strength AA 6063-T6 alloy with a durable 15-micron clear anodized surface. Our modular T-slot profiles (20, 30, 40, 45, 60, and 80 series) allow rapid, weld-free assembly of industrial automation enclosures, cleanroom workbenches, CNC router frames, and robotic safety guarding. High torsional rigidity and standardized groove geometry.",
    material: "Aluminium",
    grades: ["AA 6063-T6", "AA 6082-T6", "AA 6005A"],
    specifications: {
      "Profile Series": "20x20, 30x30, 40x40, 40x80, 45x45, 45x90, 80x80mm",
      "Groove Sizes": "6mm, 8mm, and 10mm T-slot standard",
      "Anodizing": "15 Micron satin matte natural anodized (Silver / Black)",
      "Straightness Tolerance": "0.5mm per 1000mm length",
    },
    applications: [
      "Automated assembly lines and conveyor side frames",
      "Robotic workcells and safety fencing enclosures",
      "Ergonomic industrial assembly workstations and test benches",
      "3D printer and CNC gantry structural frameworks",
    ],
    manufacturing_process: [
      "Direct extrusion on 2,500-ton modern extrusion press",
      "Controlled nitrogen shroud die cooling",
      "Artificial aging oven heat treatment to T6 hardness",
      "Automated acid etch and electrolytic clear anodizing",
    ],
    technical_info: {
      "Hardness": "Min 11-13 Webster (75-85 Brinell)",
      "Connection Method": "Pre-drilled core for M8/M12 taps, universal bracket assembly",
    },
    image_url:
      "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
    is_featured: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-08",
    name: "Architectural Aluminium Facade & Curtain Wall Sections",
    slug: "architectural-aluminium-curtain-wall",
    category: "Aluminium Products",
    subcategory: "Aluminium Sections",
    short_description:
      "Custom engineered structural mullions and transoms for high-wind commercial building facades and glass envelopes.",
    description:
      "Heavy-duty architectural aluminium extrusion systems engineered to absorb high wind pressures and thermal movements in high-rise facades. Available in thermally broken designs, PVDF fluorocarbon coatings (AAMA 2605 compliant, 20-year warranty), or wood-grain sublimation finishes. Precision engineered pressure plates, gaskets, and snap-on caps.",
    material: "Aluminium",
    grades: ["AA 6063-T6", "AA 6061-T6"],
    specifications: {
      "Mullion Depths": "50mm to 250mm structural depths",
      "Wall Thickness": "2.5mm to 4.0mm heavy commercial gauge",
      "Surface Finish": "PVDF 3-coat (35 microns) or Polyester Powder Coating (60-80 microns)",
      "Wind Load Rating": "Engineered for pressures up to 3.5 kPa",
    },
    applications: [
      "Commercial IT park glazed curtain walls and skylights",
      "Airport terminal monumental glass facades",
      "Hospital building envelope thermal barrier systems",
      "High-rise luxury residential unitized facade panels",
    ],
    manufacturing_process: [
      "Precision multi-cavity extrusion with internal thermal break slotting",
      "Polyamide structural thermal strip crimping",
      "Automated vertical powder coating line with chrome-free pre-treatment",
      "CNC end-milling and drainage slot punching",
    ],
    technical_info: {
      "Air Infiltration": "ASTM E283 compliant (< 0.06 cfm/sqft)",
      "Water Resistance": "ASTM E331 test passing 720 Pa static pressure",
    },
    image_url:
      "https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=800&q=80",
    is_featured: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-09",
    name: "Aluminium Marine & Industrial Sheets / Plates (5052 / 6061)",
    slug: "aluminium-industrial-sheets-plates",
    category: "Aluminium Products",
    subcategory: "Aluminium Sheets",
    short_description:
      "Corrosion-resistant aluminium sheets, 5-bar chequered plates, and tooling plates for maritime and defense uses.",
    description:
      "High-grade magnesium-alloyed aluminium plates offering outstanding resistance to saltwater atmosphere, aggressive industrial chemicals, and stress corrosion cracking. Mill-finished or mirror-polished sheets for fuel tanks, railway coaches, non-slip marine walkways, and electronics chassis.",
    material: "Aluminium",
    grades: ["AA 5052-H32", "AA 5083-H111", "AA 6061-T651", "AA 7075-T651"],
    specifications: {
      "Sheet Thickness": "0.8mm to 6.0mm",
      "Plate Thickness": "6.0mm to 100mm (Precision milled plates)",
      "Patterns": "5-Bar chequered tread pattern, Diamond pattern, Plain smooth",
      "Standard Sheet Sizes": "1250 x 2500mm, 1500 x 3000mm, 2000 x 4000mm",
    },
    applications: [
      "Shipbuilding hulls, superstructures, and offshore gangways",
      "Vande Bharat / Metro train passenger coach interior floors and panels",
      "Cryogenic liquid natural gas storage vessel linings",
      "Precision tooling jigs and semiconductor fixture plates",
    ],
    manufacturing_process: [
      "Continuous direct chill casting of prime high-purity ingots",
      "Hot breakdown rolling mill followed by cold finishing stands",
      "Controlled tension leveling for dead-flat panel flatness",
      "Protective laser-cutting grade PE film lamination",
    ],
    technical_info: {
      "Salt Spray Test": "Exceeds 1,000 hours ASTM B117 salt spray testing without pitting",
      "Bendability": "90° cold bend radius down to 1.5t without surface micro-cracks",
    },
    image_url:
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    is_featured: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-10",
    name: "Aluminium Solar PV Module Mounting Structures",
    slug: "aluminium-solar-mounting-structures",
    category: "Aluminium Products",
    subcategory: "Aluminium Frames",
    short_description:
      "High-yield extruded aluminium racking rails and mid/end clamp brackets engineered for 180 km/h cyclone resistance.",
    description:
      "Lightweight yet structurally formidable solar mounting profiles engineered for utility-scale ground mount solar parks and industrial rooftop installations. Made from 6005A-T6 and 6063-T6 with hot-dip anodized coating (12-15 microns) ensuring 25-year maintenance-free operational life in harsh tropical outdoor climates.",
    material: "Aluminium",
    grades: ["AA 6005A-T6", "AA 6063-T6"],
    specifications: {
      "Rail Profiles": "SR-40, SR-50, SR-60 reinforced C-slot rails",
      "Clamp Systems": "Integrated grounding mid-clamps and end-clamps for 30-40mm modules",
      "Wind Speed Certification": "Certified for gusts up to 180 km/h (IS 875 Part 3)",
      "Hardware": "SS304 / SS316 fasteners with anti-galling lubrication",
    },
    applications: [
      "Megawatt utility scale solar power generation plants",
      "Commercial and industrial factory rooftop solar plants",
      "Solar parking carports and canopy installations",
      "Agri-photovoltaic elevated mounting systems",
    ],
    manufacturing_process: [
      "High-speed multi-hole extrusion profiling",
      "Inline high-accuracy automated punch punching for slot holes",
      "Batch anodization and automated bundling",
    ],
    technical_info: {
      "Weight Saving": "60% lighter than structural hot-dip galvanized steel",
      "Corrosion Rating": "Class C4 industrial atmosphere durability",
    },
    image_url:
      "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80",
    is_featured: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-11",
    name: "Heavy CNC Machined Components & Large Flanges",
    slug: "heavy-cnc-machined-components",
    category: "Custom Products",
    subcategory: "CNC Components",
    short_description:
      "Precision 5-axis CNC milled and turned steel and aluminium industrial components with sub-micron tolerances.",
    description:
      "Equipped with large bed CNC vertical machining centers (VMCs), horizontal boring machines, and CNC vertical turret lathes (VTL) capable of machining diameters up to 3,000mm. We manufacture critical power generation flanges, gearbox housings, excavator knuckle brackets, and hydraulic manifold blocks with full CMM inspection.",
    material: "Alloy",
    grades: ["Forged Steel ASTM A105", "Alloy Steel 42CrMo4 / EN19", "Aluminium 7075-T6"],
    specifications: {
      "Maximum Turning Diameter": "Up to 3,200mm on CNC VTL",
      "Maximum Milling Envelope": "X: 4,000mm | Y: 2,500mm | Z: 1,500mm",
      "Positional Accuracy": "± 0.005mm (5 microns)",
      "Surface Roughness": "Ra down to 0.4 µm",
    },
    applications: [
      "High-pressure piping pipeline companion flanges and blind flanges",
      "Hydro turbine casing components and shaft collars",
      "Defense tracked vehicle suspension arms",
      "Industrial pump casings and centrifugal compressor impellers",
    ],
    manufacturing_process: [
      "Ultrasonically inspected prime forgings / rolled rings",
      "Rough CNC turning and stress relief annealing",
      "High-precision 5-axis finish milling",
      "Co-ordinate Measuring Machine (CMM) multi-point dimensional validation",
    ],
    technical_info: {
      "Inspection": "Zeiss 3D CMM inspection report provided with every batch",
      "Balancing": "Dynamic balancing conforming to ISO 1940 Grade G2.5",
    },
    image_url:
      "https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=800&q=80",
    is_featured: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
  {
    id: "prod-12",
    name: "Pre-Engineered Building (PEB) Structural Members",
    slug: "peb-structural-members",
    category: "Fabricated Structures",
    subcategory: "Fabricated Structures",
    short_description:
      "Custom tapered rafters, built-up rigid frames, and high-tensile cold-formed Z/C purlins for rapid erection.",
    description:
      "End-to-end engineered steel building framing solutions fabricated using automated submerged arc welding lines. Tailored for logistics hubs, cold storages, heavy manufacturing plants, and sports arenas. Optimized flange-and-web thickness tapering minimizes dead weight while maximizing clear spans up to 60 meters without intermediate columns.",
    material: "Steel",
    grades: ["IS 2062 E350 (Plate)", "ASTM A572 Gr 50", "High Tensile Galv Steel 350-450 MPa (Purlins)"],
    specifications: {
      "Clear Span Capacity": "Up to 60 meters clear span",
      "Building Heights": "Eaves height up to 24 meters",
      "Purlin System": "High-tensile Galvalume / Galvanized Z and C sections (1.5 to 3.0mm)",
      "Roof Pitch": "Standard 1:10 or customized architectural pitch",
    },
    applications: [
      "Modern e-commerce logistics fulfillment centers (Amazon, Flipkart grade)",
      "Automobile assembly plants and stamping workshops",
      "Pharmaceutical clean warehouse facilities",
      "Aircraft maintenance hangars (MRO facilities)",
    ],
    manufacturing_process: [
      "CNC multi-torch plate stripping and beveling",
      "Automated H-beam assembly and hydraulic clamping",
      "Continuous submerged arc welding of flange-web joints",
      "Shot blasting and zinc phosphate / polyurethane shop coating",
    ],
    technical_info: {
      "Erection Speed": "Up to 40,000 sq ft framing erected per month with bolted connections",
      "Design Standards": "Designed to MBMA / AISC 360 / IS 800 standards",
    },
    image_url:
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
    is_featured: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-09-01T00:00:00Z",
  },
];

export const SEED_RFQS: RFQ[] = [
  // 1. SUBMITTED
  {
    id: "rfq-00124",
    rfq_number: "RFQ-2026-00124",
    customer_id: "usr-cust-01",
    product_id: "prod-01",
    product_name: "Heavy Structural Steel Beams (ISMB / UB)",
    title: "Structural Steel Beams for Mumbai Coastal Road Connector",
    description:
      "Procurement of 120 Metric Tons of ISMB 450 and ISMB 500 Grade E350 steel beams with SA 2.5 shot blast and inorganic zinc silicate shop primer. Required for elevated viaduct gantry support.",
    quantity: 120,
    unit: "Tons",
    material: "Steel",
    specifications: {
      grade: "IS 2062 Grade E350",
      dimensions: "ISMB 450 (86.9 kg/m) & ISMB 500 (95.2 kg/m)",
      surfaceFinish: "Shot blasted SA 2.5 + 75µm Zinc Silicate Primer",
      tolerance: "IS 1852 strictly compliant",
      length: "12.0 Meter fixed lengths",
    },
    priority: "HIGH",
    status: "SUBMITTED",
    delivery_date: "2026-10-15",
    estimated_value: 8200000,
    created_at: "2026-09-10T08:30:00Z",
    updated_at: "2026-09-10T08:30:00Z",
    attachments: [
      {
        id: "att-01",
        rfq_id: "rfq-00124",
        file_name: "Gantry_Structural_Drawing_RevB.pdf",
        file_url: "/uploads/drawings/Gantry_Structural_Drawing_RevB.pdf",
        file_type: "application/pdf",
        file_size: 4250000,
        created_at: "2026-09-10T08:30:00Z",
      },
      {
        id: "att-02",
        rfq_id: "rfq-00124",
        file_name: "Tender_BoQ_Steel_Spec.xlsx",
        file_url: "/uploads/drawings/Tender_BoQ_Steel_Spec.xlsx",
        file_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        file_size: 1120000,
        created_at: "2026-09-10T08:30:00Z",
      },
    ],
  },
  // 2. UNDER_REVIEW
  {
    id: "rfq-00123",
    rfq_number: "RFQ-2026-00123",
    customer_id: "usr-cust-02",
    product_id: "prod-06",
    product_name: "Custom Welded Box Girders & Built-up Columns",
    title: "Welded Crane Runway Box Girders (50T EOT Duty)",
    description:
      "Fabrication of 8 continuous welded box girders (depth 1800mm, span 24m) for heavy foundry workshop crane runway. Full UT on tension welds.",
    quantity: 8,
    unit: "Assemblies",
    material: "Steel",
    specifications: {
      grade: "IS 2062 E350 BO with sub-zero impact testing at -20°C",
      dimensions: "1800mm Web x 600mm Flange x 24m Length",
      surfaceFinish: "Epoxy PU high build 300 microns",
      camber: "Positive pre-camber 18mm at mid-span",
    },
    priority: "URGENT",
    status: "UNDER_REVIEW",
    delivery_date: "2026-11-01",
    assigned_to: "Rajesh Kulkarni",
    assigned_engineer_email: "rajesh.k@steelcoreindustries.com",
    estimated_value: 14500000,
    created_at: "2026-09-08T11:15:00Z",
    updated_at: "2026-09-09T14:20:00Z",
    attachments: [
      {
        id: "att-03",
        rfq_id: "rfq-00123",
        file_name: "Crane_Box_Girder_WPS_Rev1.pdf",
        file_url: "/uploads/drawings/Crane_Box_Girder_WPS_Rev1.pdf",
        file_type: "application/pdf",
        file_size: 6100000,
        created_at: "2026-09-08T11:15:00Z",
      },
    ],
  },
  // 3. NEED_INFORMATION
  {
    id: "rfq-00122",
    rfq_number: "RFQ-2026-00122",
    customer_id: "usr-cust-03",
    product_id: "prod-04",
    product_name: "High-Strength Steel Plates (IS 2062 E250 / E350)",
    title: "Heavy Base Plates for Transmission Substation Columns",
    description:
      "65 Metric Tons of 50mm and 65mm thick steel base plates with precision CNC drilled anchor bolt holes. Awaiting foundation anchor bolt center distance confirmation from customer.",
    quantity: 65,
    unit: "Tons",
    material: "Steel",
    specifications: {
      grade: "IS 2062 E350 BR",
      thickness: "50mm & 65mm",
      drilling: "32 holes of 48mm dia per plate",
    },
    priority: "HIGH",
    status: "NEED_INFORMATION",
    delivery_date: "2026-10-25",
    assigned_to: "Vikramaditya Mehta",
    assigned_engineer_email: "admin@steelcoreindustries.com",
    estimated_value: 4850000,
    created_at: "2026-09-07T09:00:00Z",
    updated_at: "2026-09-08T16:45:00Z",
  },
  // 4. QUOTATION_PREPARED
  {
    id: "rfq-00121",
    rfq_number: "RFQ-2026-00121",
    customer_id: "usr-cust-04",
    product_id: "prod-10",
    product_name: "Aluminium Solar PV Module Mounting Structures",
    title: "15 MW Rajasthan Solar Farm Extruded Aluminium Racking",
    description:
      "Engineered aluminium rails and anodized mid/end clamps for 15 MW ground-mount utility project. 15-micron clear anodized AA 6005A-T6.",
    quantity: 450,
    unit: "MT",
    material: "Aluminium",
    specifications: {
      grade: "AA 6005A-T6",
      anodizing: "15 Micron Natural Matte Clear",
      windLoad: "175 km/h engineered certificate",
    },
    priority: "NORMAL",
    status: "QUOTATION_PREPARED",
    delivery_date: "2026-12-05",
    assigned_to: "Rajesh Kulkarni",
    assigned_engineer_email: "rajesh.k@steelcoreindustries.com",
    estimated_value: 98000000,
    created_at: "2026-09-05T10:00:00Z",
    updated_at: "2026-09-09T17:00:00Z",
  },
  // 5. QUOTATION_SENT
  {
    id: "rfq-00120",
    rfq_number: "RFQ-2026-00120",
    customer_id: "usr-cust-01",
    product_id: "prod-07",
    product_name: "Industrial Aluminium Modular T-Slot Profiles",
    title: "Automated Conveyor Line T-Slot 45x90 Profiles",
    description:
      "4,200 meters of 45x90 heavy series aluminium modular profiles with pre-machined connector holes, end caps, and gusset brackets.",
    quantity: 4200,
    unit: "Meters",
    material: "Aluminium",
    specifications: {
      grade: "AA 6063-T6",
      section: "45x90 Heavy 10-Slot",
      finish: "Natural Silver Anodized 15 Micron",
    },
    priority: "NORMAL",
    status: "QUOTATION_SENT",
    delivery_date: "2026-10-10",
    assigned_to: "Vikramaditya Mehta",
    assigned_engineer_email: "admin@steelcoreindustries.com",
    quotation_id: "quote-0052",
    estimated_value: 3650000,
    created_at: "2026-09-03T14:00:00Z",
    updated_at: "2026-09-06T11:30:00Z",
  },
  // 6. APPROVED
  {
    id: "rfq-00119",
    rfq_number: "RFQ-2026-00119",
    customer_id: "usr-cust-05",
    product_id: "prod-05",
    product_name: "Heavy Steel Pipes & Hollow Sections (SHS / RHS / CHS)",
    title: "Rectangular Hollow Sections (RHS 300x200x12) for JSW Coal Conveyor",
    description:
      "180 Metric Tons of Grade YSt 355 RHS for 2.4 km overhead belt conveyor gallery.",
    quantity: 180,
    unit: "Tons",
    material: "Steel",
    specifications: {
      grade: "IS 4923 YSt 355",
      size: "300 x 200 x 12.0 mm",
      length: "12.0m standard with mill test 3.1",
    },
    priority: "HIGH",
    status: "APPROVED",
    delivery_date: "2026-10-30",
    assigned_to: "Rajesh Kulkarni",
    assigned_engineer_email: "rajesh.k@steelcoreindustries.com",
    quotation_id: "quote-0048",
    estimated_value: 12960000,
    created_at: "2026-08-28T09:30:00Z",
    updated_at: "2026-09-04T16:00:00Z",
  },
  // 7. IN_PRODUCTION
  {
    id: "rfq-00118",
    rfq_number: "RFQ-2026-00118",
    customer_id: "usr-cust-07",
    product_id: "prod-12",
    product_name: "Pre-Engineered Building (PEB) Structural Members",
    title: "180,000 Sq Ft Warehouse PEB Framing at Chakan MIDC",
    description:
      "Complete PEB primary framing: tapered built-up portal frames, crane bracket columns (10T crane rating), high-tensile galvanised Z-purlins, and bracing assemblies.",
    quantity: 580,
    unit: "Tons",
    material: "Steel",
    specifications: {
      grade: "IS 2062 E350 (Frames) / Galv 450 MPa (Purlins)",
      span: "36m Clear Span x 120m Length x 12m Clear Height",
      coating: "Shot blast SA 2.5 + 100µm DFT Zinc Phosphate Primer",
    },
    priority: "URGENT",
    status: "IN_PRODUCTION",
    delivery_date: "2026-11-15",
    assigned_to: "Vikramaditya Mehta",
    assigned_engineer_email: "admin@steelcoreindustries.com",
    quotation_id: "quote-0045",
    estimated_value: 46400000,
    created_at: "2026-08-15T08:00:00Z",
    updated_at: "2026-09-01T10:00:00Z",
  },
  // 8. COMPLETED
  {
    id: "rfq-00117",
    rfq_number: "RFQ-2026-00117",
    customer_id: "usr-cust-08",
    product_id: "prod-06",
    product_name: "Custom Welded Box Girders & Built-up Columns",
    title: "Hyderabad Metro Elevated Pier Cap Steel Girders",
    description:
      "Fabrication and trial shop assembly of 16 heavy composite pier cap steel girders for station viaduct interchange. Delivered with TUV 100% NDT clearance.",
    quantity: 16,
    unit: "Assemblies",
    material: "Steel",
    specifications: {
      grade: "IS 2062 Grade E350 C",
      weight: "28 Tons per girder",
      inspection: "Third-party inspection by TUV India",
    },
    priority: "HIGH",
    status: "COMPLETED",
    delivery_date: "2026-08-20",
    assigned_to: "Rajesh Kulkarni",
    assigned_engineer_email: "rajesh.k@steelcoreindustries.com",
    quotation_id: "quote-0038",
    estimated_value: 33600000,
    created_at: "2026-06-10T10:00:00Z",
    updated_at: "2026-08-25T15:30:00Z",
  },
  // 9. REJECTED
  {
    id: "rfq-00116",
    rfq_number: "RFQ-2026-00116",
    customer_id: "usr-cust-09",
    product_id: "prod-11",
    product_name: "Heavy CNC Machined Components & Large Flanges",
    title: "Ultra-High Carbon Tool Steel Mandrels (Outside Manufacturing Scope)",
    description:
      "Tungsten carbide tipped deep-hole forging mandrels. Rejected during technical evaluation as our equipment specializes in heavy structural & structural alloy components, not specialized carbide tooling.",
    quantity: 10,
    unit: "Pieces",
    material: "Custom Alloy",
    specifications: {
      grade: "AISI D2 Tool Steel with Carbide Inserts",
      hardness: "62 HRC",
    },
    priority: "LOW",
    status: "REJECTED",
    delivery_date: "2026-09-30",
    assigned_to: "Vikramaditya Mehta",
    assigned_engineer_email: "admin@steelcoreindustries.com",
    estimated_value: 1200000,
    created_at: "2026-08-20T11:00:00Z",
    updated_at: "2026-08-22T17:00:00Z",
  },
  // 10. CANCELLED
  {
    id: "rfq-00115",
    rfq_number: "RFQ-2026-00115",
    customer_id: "usr-cust-10",
    product_id: "prod-02",
    product_name: "Structural Steel Channels (ISMC)",
    title: "Boiler Support Channels ISMC 300 - Project Postponed by Client",
    description:
      "Customer informed that the thermal power revamp tender has been deferred by government authorities to next fiscal year. RFQ cancelled by customer request.",
    quantity: 90,
    unit: "Tons",
    material: "Steel",
    specifications: {
      grade: "IS 2062 E250",
      section: "ISMC 300x90",
    },
    priority: "LOW",
    status: "CANCELLED",
    delivery_date: "2026-10-15",
    assigned_to: "Rajesh Kulkarni",
    assigned_engineer_email: "rajesh.k@steelcoreindustries.com",
    estimated_value: 5850000,
    created_at: "2026-08-10T14:30:00Z",
    updated_at: "2026-08-18T12:00:00Z",
  },
  // Additional 20 RFQs to complete a rich 30 RFQ dataset
  {
    id: "rfq-00114",
    rfq_number: "RFQ-2026-00114",
    customer_id: "usr-cust-06",
    product_id: "prod-09",
    product_name: "Aluminium Marine & Industrial Sheets / Plates",
    title: "AA 5083-H111 Marine Plates for High-Speed Patrol Craft",
    description: "45 Tons of 8mm & 12mm DNV-certified marine aluminium sheets for naval hull plating.",
    quantity: 45,
    unit: "Tons",
    material: "Aluminium",
    specifications: { grade: "AA 5083-H111", certification: "DNV / Lloyd's Register 3.2" },
    priority: "HIGH",
    status: "IN_PRODUCTION",
    delivery_date: "2026-10-20",
    assigned_to: "Rajesh Kulkarni",
    estimated_value: 16200000,
    created_at: "2026-08-01T10:00:00Z",
    updated_at: "2026-08-28T14:00:00Z",
  },
  {
    id: "rfq-00113",
    rfq_number: "RFQ-2026-00113",
    customer_id: "usr-cust-02",
    product_id: "prod-04",
    product_name: "High-Strength Steel Plates (IS 2062 E250 / E350)",
    title: "Reactor Vessel Foundation Base Plates (SA 516 Gr 70)",
    description: "110 Tons of normalized 70mm pressure vessel plates for petrochemical refinery expansion in Dahej.",
    quantity: 110,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "ASTM SA 516 Grade 70 Normalized", thickness: "70mm" },
    priority: "HIGH",
    status: "APPROVED",
    delivery_date: "2026-11-20",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 9900000,
    created_at: "2026-07-25T11:30:00Z",
    updated_at: "2026-08-20T16:00:00Z",
  },
  {
    id: "rfq-00112",
    rfq_number: "RFQ-2026-00112",
    customer_id: "usr-cust-03",
    product_id: "prod-01",
    product_name: "Heavy Structural Steel Beams (ISMB / UB)",
    title: "Universal Beams UB 610x229 for Highway Flyover",
    description: "210 Metric Tons of parallel flange beams conforming to EN 10025 S355JR.",
    quantity: 210,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "EN 10025 S355JR", size: "UB 610x229x125 kg/m" },
    priority: "NORMAL",
    status: "QUOTATION_SENT",
    delivery_date: "2026-11-05",
    assigned_to: "Rajesh Kulkarni",
    quotation_id: "quote-0050",
    estimated_value: 15750000,
    created_at: "2026-08-05T09:00:00Z",
    updated_at: "2026-08-22T10:30:00Z",
  },
  {
    id: "rfq-00111",
    rfq_number: "RFQ-2026-00111",
    customer_id: "usr-cust-04",
    product_id: "prod-08",
    product_name: "Architectural Aluminium Facade & Curtain Wall Sections",
    title: "Curtain Wall Mullions for Chennai Tech Park Tower 2",
    description: "32 Metric Tons of custom PVDF-coated aluminium mullions (200mm depth) with thermal barrier strips.",
    quantity: 32,
    unit: "Tons",
    material: "Aluminium",
    specifications: { grade: "AA 6063-T6", finish: "3-Coat PVDF Charcoal Grey Metallic" },
    priority: "NORMAL",
    status: "UNDER_REVIEW",
    delivery_date: "2026-12-15",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 10240000,
    created_at: "2026-08-29T14:00:00Z",
    updated_at: "2026-09-02T11:00:00Z",
  },
  {
    id: "rfq-00110",
    rfq_number: "RFQ-2026-00110",
    customer_id: "usr-cust-07",
    product_id: "prod-03",
    product_name: "Structural Equal & Unequal Angles (ISA)",
    title: "Heavy Equal Angles ISA 150x150x15 for Industrial Sheds",
    description: "75 Tons of equal angle bracing sections for logistics depot in NCR.",
    quantity: 75,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "IS 2062 E250", size: "ISA 150x150x15mm" },
    priority: "NORMAL",
    status: "QUOTATION_PREPARED",
    delivery_date: "2026-10-18",
    assigned_to: "Rajesh Kulkarni",
    estimated_value: 4875000,
    created_at: "2026-08-22T15:30:00Z",
    updated_at: "2026-09-01T16:20:00Z",
  },
  {
    id: "rfq-00109",
    rfq_number: "RFQ-2026-00109",
    customer_id: "usr-cust-05",
    product_id: "prod-06",
    product_name: "Custom Welded Box Girders & Built-up Columns",
    title: "Cruciform Built-Up Columns for High-Rise Commercial Mall",
    description: "16 cruciform welded heavy column members with internal continuity stiffeners.",
    quantity: 16,
    unit: "Assemblies",
    material: "Steel",
    specifications: { grade: "IS 2062 E350", weight: "18 Tons each" },
    priority: "HIGH",
    status: "IN_PRODUCTION",
    delivery_date: "2026-11-10",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 23040000,
    created_at: "2026-07-15T10:00:00Z",
    updated_at: "2026-08-25T12:00:00Z",
  },
  {
    id: "rfq-00108",
    rfq_number: "RFQ-2026-00108",
    customer_id: "usr-cust-09",
    product_id: "prod-11",
    product_name: "Heavy CNC Machined Components & Large Flanges",
    title: "Precision VTL Turned High-Pressure Blind Flanges 42 Inch",
    description: "24 blind flanges forged ASTM A105 machined to ASME B16.47 Class 600.",
    quantity: 24,
    unit: "Pieces",
    material: "Steel",
    specifications: { standard: "ASME B16.47 Series A", rating: "Class 600" },
    priority: "HIGH",
    status: "APPROVED",
    delivery_date: "2026-10-28",
    assigned_to: "Rajesh Kulkarni",
    estimated_value: 6240000,
    created_at: "2026-07-28T16:00:00Z",
    updated_at: "2026-08-30T10:00:00Z",
  },
  {
    id: "rfq-00107",
    rfq_number: "RFQ-2026-00107",
    customer_id: "usr-cust-08",
    product_id: "prod-05",
    product_name: "Heavy Steel Pipes & Hollow Sections (SHS / RHS / CHS)",
    title: "Circular Hollow Sections (CHS 508mm x 16mm) for Metro Stations",
    description: "140 Tons of structural tubular columns with welded conical base stubs.",
    quantity: 140,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "IS 4923 YSt 310", size: "508mm OD x 16mm thick" },
    priority: "NORMAL",
    status: "COMPLETED",
    delivery_date: "2026-08-15",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 10920000,
    created_at: "2026-06-01T09:00:00Z",
    updated_at: "2026-08-18T11:00:00Z",
  },
  {
    id: "rfq-00106",
    rfq_number: "RFQ-2026-00106",
    customer_id: "usr-cust-01",
    product_id: "prod-04",
    product_name: "High-Strength Steel Plates (IS 2062 E250 / E350)",
    title: "Wear Resistant Steel Plates for Concrete Batching Plant Liners",
    description: "35 Tons of 16mm and 20mm abrasion resistant 400 BHN steel plates cut to profile.",
    quantity: 35,
    unit: "Tons",
    material: "Steel",
    specifications: { hardness: "400 HBW", cutting: "CNC underwater plasma cutting" },
    priority: "NORMAL",
    status: "COMPLETED",
    delivery_date: "2026-07-30",
    assigned_to: "Rajesh Kulkarni",
    estimated_value: 3675000,
    created_at: "2026-05-15T11:00:00Z",
    updated_at: "2026-08-01T15:00:00Z",
  },
  {
    id: "rfq-00105",
    rfq_number: "RFQ-2026-00105",
    customer_id: "usr-cust-10",
    product_id: "prod-06",
    product_name: "Custom Welded Box Girders & Built-up Columns",
    title: "Heavy Boiler Support Girders for NTPC Thermal Unit",
    description: "4 heavy welded plate girders of 3.2m depth with ultrasonic examination.",
    quantity: 4,
    unit: "Assemblies",
    material: "Steel",
    specifications: { grade: "IS 2062 E350 C", weight: "42 Tons each" },
    priority: "HIGH",
    status: "COMPLETED",
    delivery_date: "2026-07-15",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 16800000,
    created_at: "2026-04-10T10:00:00Z",
    updated_at: "2026-07-20T17:00:00Z",
  },
  {
    id: "rfq-00104",
    rfq_number: "RFQ-2026-00104",
    customer_id: "usr-cust-02",
    product_id: "prod-10",
    product_name: "Aluminium Solar PV Module Mounting Structures",
    title: "Solar Carport Canopies for L&T Knowledge City Vadodara",
    description: "60 Metric tons of anodized 6005A-T6 profiles for 1.8 MW solar car parking structure.",
    quantity: 60,
    unit: "MT",
    material: "Aluminium",
    specifications: { grade: "AA 6005A-T6", coating: "15µm Natural Silver Anodize" },
    priority: "NORMAL",
    status: "COMPLETED",
    delivery_date: "2026-06-25",
    assigned_to: "Rajesh Kulkarni",
    estimated_value: 13800000,
    created_at: "2026-03-20T08:30:00Z",
    updated_at: "2026-06-30T10:00:00Z",
  },
  {
    id: "rfq-00103",
    rfq_number: "RFQ-2026-00103",
    customer_id: "usr-cust-04",
    product_id: "prod-07",
    product_name: "Industrial Aluminium Modular T-Slot Profiles",
    title: "Cleanroom Workstations Profile Kits for Electronics Plant",
    description: "50 flat-pack kit sets of 40x40 modular profile assembly tables with antistatic feet.",
    quantity: 50,
    unit: "Pieces",
    material: "Aluminium",
    specifications: { series: "40x40 Heavy", accessories: "Complete connector pack" },
    priority: "LOW",
    status: "COMPLETED",
    delivery_date: "2026-05-30",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 1850000,
    created_at: "2026-03-10T14:00:00Z",
    updated_at: "2026-06-05T12:00:00Z",
  },
  {
    id: "rfq-00102",
    rfq_number: "RFQ-2026-00102",
    customer_id: "usr-cust-06",
    product_id: "prod-11",
    product_name: "Heavy CNC Machined Components & Large Flanges",
    title: "Titanium & 7075 Aerospace Fixture Baseplates",
    description: "High-precision 7075-T651 jig plates machined on 5-axis CNC with ±0.005mm tolerance.",
    quantity: 12,
    unit: "Pieces",
    material: "Custom Alloy",
    specifications: { grade: "AA 7075-T651", flatness: "0.01mm across 1500mm" },
    priority: "URGENT",
    status: "COMPLETED",
    delivery_date: "2026-06-15",
    assigned_to: "Rajesh Kulkarni",
    estimated_value: 4200000,
    created_at: "2026-03-05T11:00:00Z",
    updated_at: "2026-06-20T14:00:00Z",
  },
  {
    id: "rfq-00101",
    rfq_number: "RFQ-2026-00101",
    customer_id: "usr-cust-07",
    product_id: "prod-12",
    product_name: "Pre-Engineered Building (PEB) Structural Members",
    title: "Cold Storage Facility PEB Frame - 40,000 Sq Ft",
    description: "Insulated sandwich panel compatible portal framing with polyisocyanurate thermal bridge details.",
    quantity: 140,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "IS 2062 E350", protection: "Epoxy PU 250 microns" },
    priority: "NORMAL",
    status: "COMPLETED",
    delivery_date: "2026-04-30",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 11900000,
    created_at: "2026-02-01T09:00:00Z",
    updated_at: "2026-05-05T16:00:00Z",
  },
  {
    id: "rfq-00100",
    rfq_number: "RFQ-2026-00100",
    customer_id: "usr-cust-05",
    product_id: "prod-01",
    product_name: "Heavy Structural Steel Beams (ISMB / UB)",
    title: "ISMB 600 Columns for JSW Slag Handling Conveyor Tower",
    description: "160 Tons of heavy ISMB 600 rolled sections cut to 15m lengths with base connection plates.",
    quantity: 160,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "IS 2062 E250 BR", size: "ISMB 600 (122.6 kg/m)" },
    priority: "NORMAL",
    status: "COMPLETED",
    delivery_date: "2026-04-15",
    assigned_to: "Rajesh Kulkarni",
    estimated_value: 11200000,
    created_at: "2026-01-15T10:30:00Z",
    updated_at: "2026-04-20T10:00:00Z",
  },
  {
    id: "rfq-00099",
    rfq_number: "RFQ-2026-00099",
    customer_id: "usr-cust-03",
    product_id: "prod-05",
    product_name: "Heavy Steel Pipes & Hollow Sections (SHS / RHS / CHS)",
    title: "Square Hollow Sections (SHS 200x200x10) for Stadium Canopy",
    description: "90 Tons of cold-formed SHS certified for dynamic fatigue loading.",
    quantity: 90,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "IS 4923 YSt 355", size: "SHS 200x200x10mm" },
    priority: "HIGH",
    status: "COMPLETED",
    delivery_date: "2026-03-25",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 7020000,
    created_at: "2026-01-05T13:00:00Z",
    updated_at: "2026-03-30T17:00:00Z",
  },
  {
    id: "rfq-00098",
    rfq_number: "RFQ-2026-00098",
    customer_id: "usr-cust-08",
    product_id: "prod-02",
    product_name: "Structural Steel Channels (ISMC)",
    title: "ISMC 200 Channels for Cable Tray Support Runways",
    description: "55 Tons of hot-dip galvanized ISMC 200x75 channels (86 microns zinc coating).",
    quantity: 55,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "IS 2062 E250", coating: "HDG 86 Microns to IS 4759" },
    priority: "LOW",
    status: "COMPLETED",
    delivery_date: "2026-02-28",
    assigned_to: "Rajesh Kulkarni",
    estimated_value: 4125000,
    created_at: "2025-12-10T11:00:00Z",
    updated_at: "2026-03-05T11:00:00Z",
  },
  {
    id: "rfq-00097",
    rfq_number: "RFQ-2026-00097",
    customer_id: "usr-cust-09",
    product_id: "prod-09",
    product_name: "Aluminium Marine & Industrial Sheets / Plates",
    title: "5-Bar Aluminium Chequered Flooring Plates for Auto Transporters",
    description: "25 Tons of 4.5mm thick 5-bar chequered tread sheets for double-decker car carriers.",
    quantity: 25,
    unit: "Tons",
    material: "Aluminium",
    specifications: { grade: "AA 5052-H32", pattern: "5-Bar Chequered Tread" },
    priority: "NORMAL",
    status: "COMPLETED",
    delivery_date: "2026-02-15",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 8250000,
    created_at: "2025-11-25T14:30:00Z",
    updated_at: "2026-02-20T15:00:00Z",
  },
  {
    id: "rfq-00096",
    rfq_number: "RFQ-2026-00096",
    customer_id: "usr-cust-10",
    product_id: "prod-04",
    product_name: "High-Strength Steel Plates (IS 2062 E250 / E350)",
    title: "32mm Steel Plates for Heavy Ducting at Power Station",
    description: "80 Tons of ultrasonic grade 1 steel plates for flue gas desulfurization (FGD) ducts.",
    quantity: 80,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "IS 2062 E250 BO", thickness: "32mm" },
    priority: "NORMAL",
    status: "COMPLETED",
    delivery_date: "2026-01-20",
    assigned_to: "Rajesh Kulkarni",
    estimated_value: 5760000,
    created_at: "2025-10-20T10:00:00Z",
    updated_at: "2026-01-25T14:00:00Z",
  },
  {
    id: "rfq-00095",
    rfq_number: "RFQ-2026-00095",
    customer_id: "usr-cust-01",
    product_id: "prod-03",
    product_name: "Structural Equal & Unequal Angles (ISA)",
    title: "ISA 100x100x10 Angles for Tower Substation Pylons",
    description: "40 Tons of angle iron with pre-punched 22mm bolt holes for fast erection.",
    quantity: 40,
    unit: "Tons",
    material: "Steel",
    specifications: { grade: "IS 2062 E250", size: "ISA 100x100x10mm" },
    priority: "NORMAL",
    status: "COMPLETED",
    delivery_date: "2025-12-30",
    assigned_to: "Vikramaditya Mehta",
    estimated_value: 2680000,
    created_at: "2025-10-05T09:00:00Z",
    updated_at: "2026-01-05T12:00:00Z",
  },
];

export const SEED_RFQ_UPDATES: Record<string, RFQUpdate[]> = {
  "rfq-00124": [
    {
      id: "upd-124-1",
      rfq_id: "rfq-00124",
      admin_id: "usr-admin-01",
      admin_name: "System",
      old_status: undefined,
      new_status: "SUBMITTED",
      comment: "RFQ submitted successfully by customer Rahul Sharma (ABC Infrastructure Pvt Ltd). Reference generated: RFQ-2026-00124.",
      created_at: "2026-09-10T08:30:00Z",
    },
  ],
  "rfq-00123": [
    {
      id: "upd-123-1",
      rfq_id: "rfq-00123",
      admin_id: "usr-admin-01",
      admin_name: "System",
      old_status: undefined,
      new_status: "SUBMITTED",
      comment: "RFQ submitted for 8 units of continuous welded crane box girders.",
      created_at: "2026-09-08T11:15:00Z",
    },
    {
      id: "upd-123-2",
      rfq_id: "rfq-00123",
      admin_id: "usr-admin-02",
      admin_name: "Rajesh Kulkarni",
      old_status: "SUBMITTED",
      new_status: "UNDER_REVIEW",
      comment: "Engineering review initiated. Verifying submerged arc welding procedure specifications (WPS) and pre-camber calculations for 50T crane load.",
      created_at: "2026-09-09T14:20:00Z",
    },
  ],
  "rfq-00122": [
    {
      id: "upd-122-1",
      rfq_id: "rfq-00122",
      admin_id: "usr-admin-01",
      admin_name: "System",
      old_status: undefined,
      new_status: "SUBMITTED",
      comment: "RFQ submitted for 65 Tons of heavy steel base plates.",
      created_at: "2026-09-07T09:00:00Z",
    },
    {
      id: "upd-122-2",
      rfq_id: "rfq-00122",
      admin_id: "usr-admin-01",
      admin_name: "Vikramaditya Mehta",
      old_status: "SUBMITTED",
      new_status: "UNDER_REVIEW",
      comment: "Reviewing foundation bolt pattern on drawing Rev 01.",
      created_at: "2026-09-07T14:30:00Z",
    },
    {
      id: "upd-122-3",
      rfq_id: "rfq-00122",
      admin_id: "usr-admin-01",
      admin_name: "Vikramaditya Mehta",
      old_status: "UNDER_REVIEW",
      new_status: "NEED_INFORMATION",
      comment: "Clarification requested: Please confirm whether the 48mm anchor bolt holes require counter-boring for leveling nuts or plain through-drilling.",
      created_at: "2026-09-08T16:45:00Z",
    },
  ],
  "rfq-00121": [
    {
      id: "upd-121-1",
      rfq_id: "rfq-00121",
      admin_id: "usr-admin-01",
      admin_name: "System",
      new_status: "SUBMITTED",
      comment: "RFQ received for 450 MT aluminium solar racking extrusions.",
      created_at: "2026-09-05T10:00:00Z",
    },
    {
      id: "upd-121-2",
      rfq_id: "rfq-00121",
      admin_id: "usr-admin-02",
      admin_name: "Rajesh Kulkarni",
      old_status: "SUBMITTED",
      new_status: "UNDER_REVIEW",
      comment: "Die availability checked for SR-50 profile. Extrusion billet capacity booked on 2,500T press.",
      created_at: "2026-09-07T11:00:00Z",
    },
    {
      id: "upd-121-3",
      rfq_id: "rfq-00121",
      admin_id: "usr-admin-02",
      admin_name: "Rajesh Kulkarni",
      old_status: "UNDER_REVIEW",
      new_status: "QUOTATION_PREPARED",
      comment: "Detailed estimation ready. Extrusion rate, anodizing cost, and freight to Rajasthan compiled. Ready for dispatch.",
      created_at: "2026-09-09T17:00:00Z",
    },
  ],
  "rfq-00120": [
    {
      id: "upd-120-1",
      rfq_id: "rfq-00120",
      admin_name: "System",
      new_status: "SUBMITTED",
      comment: "RFQ received for 4,200m aluminium modular T-slot 45x90 profiles.",
      created_at: "2026-09-03T14:00:00Z",
    },
    {
      id: "upd-120-2",
      rfq_id: "rfq-00120",
      admin_name: "Vikramaditya Mehta",
      old_status: "SUBMITTED",
      new_status: "UNDER_REVIEW",
      comment: "Technical sizing verified for modular automation line.",
      created_at: "2026-09-04T10:00:00Z",
    },
    {
      id: "upd-120-3",
      rfq_id: "rfq-00120",
      admin_name: "Vikramaditya Mehta",
      old_status: "UNDER_REVIEW",
      new_status: "QUOTATION_PREPARED",
      comment: "Quotation QT-2026-0052 generated with 15-day price validity.",
      created_at: "2026-09-05T15:00:00Z",
    },
    {
      id: "upd-120-4",
      rfq_id: "rfq-00120",
      admin_name: "Vikramaditya Mehta",
      old_status: "QUOTATION_PREPARED",
      new_status: "QUOTATION_SENT",
      comment: "Formal commercial quotation QT-2026-0052 sent to customer portal. Customer notified.",
      created_at: "2026-09-06T11:30:00Z",
    },
  ],
};

export const SEED_QUOTATIONS: Quotation[] = [
  {
    id: "quote-0052",
    quotation_number: "QT-2026-0052",
    rfq_id: "rfq-00120",
    rfq_number: "RFQ-2026-00120",
    customer_id: "usr-cust-01",
    customer_name: "Rahul Sharma",
    customer_company: "ABC Infrastructure Pvt Ltd",
    items: [
      {
        id: "qi-01",
        description: "Aluminium Modular T-Slot Profile 45x90 Heavy, AA 6063-T6 Silver Anodized (6m bars)",
        quantity: 4200,
        unit: "Meters",
        unit_price: 750,
        total: 3150000,
        hsn_code: "7604",
      },
      {
        id: "qi-02",
        description: "Universal Die-Cast Aluminium Corner Bracket 45x90 with Fasteners (Set)",
        quantity: 400,
        unit: "Sets",
        unit_price: 250,
        total: 100000,
        hsn_code: "7616",
      },
      {
        id: "qi-03",
        description: "PVC End Caps for 45x90 Profile (Black)",
        quantity: 300,
        unit: "Pieces",
        unit_price: 60,
        total: 18000,
        hsn_code: "3926",
      },
    ],
    subtotal: 3268000,
    tax: 588240, // 18% GST
    shipping: 45000, // Transport to Mumbai
    discount: 50000,
    total: 3851240,
    valid_until: "2026-09-25",
    payment_terms: "30% Advance with Purchase Order, 70% against Proforma Invoice prior to dispatch.",
    delivery_terms: "Ex-Works Chakan Plant (Transport arranged to Mumbai site). Delivery in 12-15 business days.",
    notes:
      "All aluminium profiles conform to IS 733 / ASTM B221 with 15-micron architectural anodizing. Mill test certificate provided.",
    status: "SENT",
    created_at: "2026-09-06T11:30:00Z",
    updated_at: "2026-09-06T11:30:00Z",
  },
  {
    id: "quote-0048",
    quotation_number: "QT-2026-0048",
    rfq_id: "rfq-00119",
    rfq_number: "RFQ-2026-00119",
    customer_id: "usr-cust-05",
    customer_name: "Vikram Rathore",
    customer_company: "JSW Energy Logistics",
    items: [
      {
        id: "qi-04",
        description: "Rectangular Hollow Section (RHS) 300x200x12mm Grade YSt 355",
        quantity: 180,
        unit: "Tons",
        unit_price: 68500,
        total: 12330000,
        hsn_code: "7306",
      },
    ],
    subtotal: 12330000,
    tax: 2219400, // 18%
    shipping: 320000,
    discount: 100000,
    total: 14769400,
    valid_until: "2026-09-30",
    payment_terms: "LC at Sight / 60 Days Usance LC from scheduled commercial bank.",
    delivery_terms: "FOR JSW Site, Toranagallu, Karnataka in phased trailers.",
    notes: "Ultrasonic tested seam, Charpy V-notch impact passed at -20°C.",
    status: "ACCEPTED",
    created_at: "2026-08-30T10:00:00Z",
    updated_at: "2026-09-04T16:00:00Z",
  },
  {
    id: "quote-0045",
    quotation_number: "QT-2026-0045",
    rfq_id: "rfq-00118",
    rfq_number: "RFQ-2026-00118",
    customer_id: "usr-cust-07",
    customer_name: "Anand Verma",
    customer_company: "Shapoorji PEB Systems Ltd",
    items: [
      {
        id: "qi-05",
        description: "Built-up Tapered Structural Steel Portal Frames (IS 2062 E350)",
        quantity: 420,
        unit: "Tons",
        unit_price: 74000,
        total: 31080000,
        hsn_code: "7308",
      },
      {
        id: "qi-06",
        description: "High-Tensile Cold Formed Z & C Purlins 250x75x2.5mm (Galv 450 MPa)",
        quantity: 160,
        unit: "Tons",
        unit_price: 78500,
        total: 12560000,
        hsn_code: "7308",
      },
    ],
    subtotal: 43640000,
    tax: 7855200,
    shipping: 850000,
    discount: 250000,
    total: 52095200,
    valid_until: "2026-09-15",
    payment_terms: "20% Mobilization Advance, 60% running proforma against dispatch, 20% on completion.",
    delivery_terms: "Delivered to Chakan Logistics Park site.",
    notes: "Includes shop trial assembly of 2 portal frames witnessed by Shapoorji QA.",
    status: "ACCEPTED",
    created_at: "2026-08-18T10:00:00Z",
    updated_at: "2026-08-25T14:00:00Z",
  },
];

export const SEED_PROJECTS: Project[] = [
  {
    id: "proj-01",
    title: "180,000 Sq Ft PEB Heavy Industrial Logistics Depot",
    slug: "chakan-peb-logistics-depot",
    industry: "Warehousing & Logistics",
    location: "Chakan Industrial Zone, Pune, Maharashtra",
    description:
      "Engineered, fabricated, and supplied 580 metric tons of pre-engineered building portal frames with 36-meter column-free clear spans, 10-ton crane gantries, and galvanized high-tensile Z-purlin secondary structural framing.",
    materials: "IS 2062 Grade E350 Built-Up Plates, High Tensile Galvalume Purlins",
    scope: "Design Engineering + CNC Fabrication + Trial Assembly + Delivery",
    year: 2025,
    client: "Shapoorji PEB Systems & Global Logistics Hub",
    tonnage: "580 Metric Tons",
    image_url:
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    features: [
      "36-meter column-free clear span portal framing",
      "Integrated 10-ton EOT crane runways across 4 bays",
      "Submerged Arc Welded (SAW) box columns with full penetration welds",
      "Zero-defect NDT clearance with 100% UT on tension members",
    ],
    created_at: "2025-06-01T00:00:00Z",
  },
  {
    id: "proj-02",
    title: "Metro Elevated Viaduct Composite Box Girder Pier Caps",
    slug: "metro-viaduct-composite-box-girders",
    industry: "Infrastructure & Urban Rail",
    location: "Hyderabad Metro Phase 2, Telangana",
    description:
      "High-precision fabrication of 16 heavy composite steel box girders spanning 28 meters across arterial junctions. Engineered to absorb high cyclic dynamic train loadings with extreme seismic resilience.",
    materials: "IS 2062 Grade E350 C Heavy Plates up to 65mm Thickness",
    scope: "Heavy Submerged Arc Welding + 3D Laser Survey + TUV Inspection",
    year: 2025,
    client: "Hyderabad Metro Rail & L&T Infrastructure",
    tonnage: "448 Metric Tons",
    image_url:
      "https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=1200&q=80",
    features: [
      "Rigid box girder cross-sections with internal diaphragm stiffeners",
      "Laser tracker dimensional verification to ±1.5mm tolerance over 28m span",
      "3-Coat epoxy polyurethane coating with 20-year design life",
      "Trial assembled in shop prior to overnight highway transport",
    ],
    created_at: "2025-08-10T00:00:00Z",
  },
  {
    id: "proj-03",
    title: "75 MW Rajasthan Utility Solar Farm Aluminium Extrusion Mounts",
    slug: "rajasthan-solar-park-aluminium-structures",
    industry: "Renewable Energy",
    location: "Bhadla Solar Park, Rajasthan",
    description:
      "Supplied 1,850 metric tons of high-strength AA 6005A-T6 extruded aluminium mounting rails and rapid clamp fixtures designed to withstand 180 km/h desert dust cyclones with zero structural deformation.",
    materials: "Extruded Aluminium AA 6005A-T6 with 15µm Natural Anodizing",
    scope: "Custom Tooling Die Extrusion + Automated CNC Punching + Anodizing",
    year: 2024,
    client: "Mahindra Solar & State Transmission Utility",
    tonnage: "1,850 Metric Tons",
    image_url:
      "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1200&q=80",
    features: [
      "Corrosion-resistant aluminium alloy certified for 25-year desert deployment",
      "Snap-in rail geometry reducing on-site installation labor by 35%",
      "Engineered wind tunnel tested up to 180 km/h gale gusts",
      "100% recyclable environmental design",
    ],
    created_at: "2024-11-20T00:00:00Z",
  },
  {
    id: "proj-04",
    title: "Thermal Power Station Flue Gas Desulfurization (FGD) Pipe Racks",
    slug: "power-station-fgd-structural-pipe-racks",
    industry: "Heavy Engineering & Power",
    location: "Singrauli Super Thermal Power Plant, Madhya Pradesh",
    description:
      "Fabrication and hot-dip galvanizing of 920 metric tons of heavy structural steel pipe racks, galleries, and cable trays supporting high-temperature acid slurry process piping.",
    materials: "IS 2062 Grade E250 / E350 Structural Beams & Channels",
    scope: "Detailing + Automated SAW Fabrication + Heavy HDG Coating (100µm)",
    year: 2024,
    client: "BHEL Power Division & NTPC",
    tonnage: "920 Metric Tons",
    image_url:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    features: [
      "Heavy duty hot-dip galvanization strictly exceeding IS 4759 specifications",
      "Bolted connection detailing facilitating rapid shutdown installation",
      "Pre-cambered 30-meter pipe bridges across plant roadways",
    ],
    created_at: "2024-04-15T00:00:00Z",
  },
];

export const SEED_CAPABILITIES: Capability[] = [
  {
    id: "cap-01",
    name: "Heavy Structural Fabrication & Submerged Arc Welding (SAW)",
    slug: "heavy-structural-fabrication",
    machinery: "Twin-wire Gantry Submerged Arc Welding Line, 50T Overhead Cranes, Hydraulic Flange Straighteners",
    capacity: "2,500 Metric Tons per month",
    materials: ["IS 2062 E250/E350/E450", "ASTM A572 Gr 50", "EN 10025 S355JR/K2+N"],
    tolerances: "Conforms to AWS D1.1, IS 7215, and EN 1090 Execution Class EXC3",
    description:
      "Our heavy fabrication bays feature 50-metric-ton crane capacity and fully automated submerged arc welding (SAW) tractor beams. We fabricate deep plate girders, box columns, and variable depth assemblies with robotic flux recovery, precision multi-axis beveling, and controlled pre-heating.",
    applications: ["Metro & railway viaducts", "Heavy crane runway girders", "PEB mainframes", "Offshore topside structures"],
    image_url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cap-02",
    name: "High-Precision 5-Axis CNC Machining & Boring",
    slug: "cnc-machining-boring",
    machinery: "4m x 2.5m CNC Gantry Double-Column Machining Center, CNC VTL (3.2m dia), CNC Horizontal Boring Mill",
    capacity: "Sub-micron accuracy on components up to 30 metric tons",
    materials: ["Alloy Steels 42CrMo4", "Forged Steel ASTM A105", "Aluminium 7075-T6", "Stainless Steel 316L"],
    tolerances: "Positional accuracy ±0.005mm (5 µm), Surface finish Ra 0.4 µm",
    description:
      "Equipped with climate-controlled precision machining cells capable of handling monumental forgings and castings. High-torque 5-axis spindles machine complex turbine casings, heavy flange bolt circles, bearing housings, and hydraulic manifolds.",
    applications: ["High-pressure companion flanges", "Turbine and compressor housings", "Mining equipment knuckles", "Aerospace fixtures"],
    image_url: "https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cap-03",
    name: "High-Power Fiber Laser & CNC Plasma Cutting",
    slug: "fiber-laser-plasma-cutting",
    machinery: "20kW High-Power Fiber Laser (3m x 12m Bed), HD CNC Underwater Bevel Plasma (3.5m x 24m Bed)",
    capacity: "Steel cutting up to 80mm thickness, Aluminium cutting up to 50mm",
    materials: ["Carbon Steel", "High-Yield Quenched Steels", "Aluminium 5000/6000", "Wear Plates 400/500 HBW"],
    tolerances: "Laser: ±0.1mm | Plasma Bevel: ±0.5mm angle accuracy",
    description:
      "Ultramodern dual-cutting facility delivering clean, dross-free edge profiles ready for immediate welding without grinding. Automated nesting software maximizes plate yield while true-hole cutting technology produces bolt-ready holes without secondary drilling.",
    applications: ["Base plates and gusset plates", "Crane boom webs", "Heavy wear liners", "Complex architectural facade panels"],
    image_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cap-04",
    name: "Aluminium Extrusion & Heat Treatment",
    slug: "aluminium-extrusion-processing",
    machinery: "2,500-Ton & 1,800-Ton Automated Extrusion Presses, Nitrogen Shroud Dies, Aging Ovens",
    capacity: "1,200 Metric Tons of aluminium profiles per month",
    materials: ["AA 6063", "AA 6082", "AA 6005A", "AA 6061"],
    tolerances: "Strict adherence to EN 755-9 and IS 3965 precision tolerances",
    description:
      "Advanced direct extrusion presses producing custom industrial profiles, hollow architectural mullions, and solar rails up to 300mm circumscribing circle diameter (CCD). In-house computerized die workshop and computer-controlled aging ovens guarantee uniform T6 temper.",
    applications: ["Modular T-slot frames", "Curtain wall systems", "Solar module racking", "Transport vehicle body profiles"],
    image_url: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cap-05",
    name: "Surface Finishing, Shot Blasting & Powder Coating",
    slug: "surface-finishing-coating",
    machinery: "12-Wheel Continuous Roller Conveyor Shot Blasting Machine, Automated 24m Spray Booth, Vertical Anodizing Plant",
    capacity: "Surface preparation to SA 2.5 and SA 3.0, up to 100,000 sq ft per week",
    materials: ["Steel Assemblies", "Aluminium Extrusions", "Fabricated Frames"],
    tolerances: "DFT controlled to ±5 microns, Salt spray passing 1,000+ hours",
    description:
      "Comprehensive corrosion protection under one roof. Automated shot blasting removes mill scale down to white metal SA 2.5. We apply high-build epoxy zinc primers, polyurethane finishes, fireproofing intumescent coatings, or electrostatic architectural powder coating.",
    applications: ["Industrial corrosion protection", "Architectural exterior facades", "Marine environment protection", "Aesthetic machine guarding"],
    image_url: "https://images.unsplash.com/photo-1565514020179-026b92b84bb6?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cap-06",
    name: "Quality Control, Metrology & NDT Inspection",
    slug: "quality-control-ndt",
    machinery: "Carl Zeiss 3D CMM, Olympus Ultrasonic Flaw Detectors, Optical Emission Spectrometer, 1000 kN Tensile UTM",
    capacity: "100% in-house chemical, mechanical, and non-destructive testing",
    materials: ["All steel and aluminium alloys handled in the plant"],
    tolerances: "ASNT Level II / Level III certified inspection staff",
    description:
      "Zero-compromise engineering quality. In-house metallurgical laboratory conducts optical emission spectroscopy for heats verification, Charpy impact testing down to -40°C, and digital ultrasonic testing for internal flaws and weld integrity.",
    applications: ["Mill Test Certificates (EN 10204 3.1 & 3.2)", "Weld inspection reports", "Dimensional CMM validation", "Third-party audit witnessing"],
    image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80",
  },
];

export const SEED_INDUSTRIES: Industry[] = [
  {
    id: "ind-01",
    name: "Construction & Infrastructure",
    slug: "construction-infrastructure",
    description:
      "Supplying certified structural steel beams, plate girders, and composite pier caps for national highways, metro rail networks, airport expansions, and commercial high-rises.",
    hero_image: "https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=1200&q=80",
    applications: ["Metro viaducts and flyovers", "Airport terminals and monumental canopies", "High-rise core columns", "Pre-engineered warehouses"],
    key_products: ["Structural Steel Beams", "Custom Box Girders", "Steel Plates", "Hollow Sections"],
    statistics: "Over 250,000 MT of structural steel delivered to Indian infra projects",
  },
  {
    id: "ind-02",
    name: "Heavy Engineering & Power Plants",
    slug: "heavy-engineering-power",
    description:
      "Engineering robust heavy structures, boiler support frames, FGD pipe galleries, and high-pressure flanges for thermal, nuclear, hydro, and petrochemical complexes.",
    hero_image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    applications: ["Boiler structural support framing", "High-pressure companion flanges", "Acid-resistant pipe racks", "Turbine foundation embedded plates"],
    key_products: ["Welded Plate Girders", "Heavy CNC Flanges", "Pressure Vessel Plates", "ISMC Channels"],
    statistics: "Approved vendor for BHEL, NTPC, and major power OEMs",
  },
  {
    id: "ind-03",
    name: "Renewable Energy (Solar & Wind)",
    slug: "renewable-energy",
    description:
      "Precision manufactured extruded aluminium mounting structures, solar tracker torque tubes, and wind turbine structural internal tower platforms.",
    hero_image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1200&q=80",
    applications: ["Utility ground-mount racking", "Industrial rooftop clamps", "Solar tracking rails", "Wind tower internal platforms"],
    key_products: ["Aluminium Extrusion Mounts", "T-Slot Profiles", "Hot Dip Galvanized Brackets"],
    statistics: "Over 3.5 Gigawatts of solar mounting structures deployed nationwide",
  },
  {
    id: "ind-04",
    name: "Automotive & Commercial Vehicles",
    slug: "automotive-commercial-vehicles",
    description:
      "Supplying high-yield chassis channels, body cross members, lightweight aluminium tread plates, and robotic assembly tooling frames for leading automotive manufacturers.",
    hero_image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80",
    applications: ["Truck chassis side rails", "Aluminium bus body profiles", "Modular robotic welding fixtures", "Trailer chequered bed flooring"],
    key_products: ["Structural Channels (ISMC)", "Aluminium Sheets (5052)", "CNC Turned Bushings", "T-Slot Machine Guarding"],
    statistics: "Supplying top commercial vehicle OEMs in Pune and Chennai corridors",
  },
  {
    id: "ind-05",
    name: "Logistics, Warehousing & PEB Buildings",
    slug: "warehousing-peb",
    description:
      "Complete pre-engineered steel buildings, e-commerce fulfillment centers, cold storage envelopes, and automated storage and retrieval system (ASRS) racking uprights.",
    hero_image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    applications: ["E-commerce mega hubs", "Temperature-controlled cold storage", "High-bay automated pallet racking", "Crane-assisted manufacturing sheds"],
    key_products: ["PEB Structural Frames", "High-Tensile Z-Purlins", "Heavy Base Plates", "Hollow Sections"],
    statistics: "More than 5 million square feet of industrial floor area framed",
  },
  {
    id: "ind-06",
    name: "Marine, Defense & Rail Transit",
    slug: "marine-defense-railways",
    description:
      "Supplying DNV-certified saltwater-resistant aluminium plates (5083), railway coach structural members for Vande Bharat trainsets, and defense vehicle sub-assemblies.",
    hero_image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    applications: ["High-speed patrol boat hulls", "Passenger train coach interior structures", "Armored vehicle bracket forgings", "Naval radar mounting towers"],
    key_products: ["Marine Aluminium Plates (5083)", "Heavy CNC Flanges", "Precision Extruded Profiles"],
    statistics: "Direct supplier to defense shipyards and rail coach factories",
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-01",
    user_id: "usr-cust-01",
    rfq_id: "rfq-00120",
    quotation_id: "quote-0052",
    title: "Quotation Received: QT-2026-0052",
    message:
      "STEELCORE Engineering has prepared and sent formal quotation QT-2026-0052 for your RFQ-2026-00120 (Aluminium Modular T-Slot Profiles).",
    is_read: false,
    link: "/customer/quotations/quote-0052",
    created_at: "2026-09-06T11:30:00Z",
  },
  {
    id: "notif-02",
    user_id: "usr-cust-01",
    rfq_id: "rfq-00124",
    title: "RFQ Submitted: RFQ-2026-00124",
    message: "Your quotation request for Structural Steel Beams has been received and queued for technical engineering review.",
    is_read: false,
    link: "/customer/requests/rfq-00124",
    created_at: "2026-09-10T08:30:00Z",
  },
  {
    id: "notif-03",
    user_id: "usr-admin-01",
    rfq_id: "rfq-00124",
    title: "New Incoming RFQ: RFQ-2026-00124",
    message: "ABC Infrastructure Pvt Ltd submitted RFQ for 120 Tons of Structural Steel Beams. High priority project.",
    is_read: false,
    link: "/admin/requests/rfq-00124",
    created_at: "2026-09-10T08:30:00Z",
  },
  {
    id: "notif-04",
    user_id: "usr-admin-01",
    rfq_id: "rfq-00119",
    quotation_id: "quote-0048",
    title: "Quotation Accepted: QT-2026-0048",
    message: "JSW Energy Logistics accepted Quotation QT-2026-0048 for RHS Sections. Status upgraded to APPROVED.",
    is_read: true,
    link: "/admin/requests/rfq-00119",
    created_at: "2026-09-04T16:00:00Z",
  },
];
